stages:
  - test

laravel_tests:
  stage: test
  image: php:8.4-cli

  before_script:
    - apt-get update && apt-get install -y git unzip libzip-dev
    - docker-php-ext-install pdo_mysql zip

    - curl -sS https://getcomposer.org/installer | php
    - mv composer.phar /usr/local/bin/composer

  script:
    - composer install
    - cp .env.example .env
    - php artisan key:generate
    - php artisan test
